name: valutx
dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  webauthn: ^0.2.5
  flutter_secure_storage: ^9.2.4
  local_auth: ^2.1.0
  encrypt: ^5.0.0
  device_info_plus: ^11.3.0
  firebase_messaging: ^15.2.3
  flutter_local_notifications: ^18.0.1
  firebase_core: ^3.12.0
  timezone: ^0.10.0

environment:
  sdk: '^3.7.0'
